name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Hinzugefügt
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get ECR Login Password (Debug)
      run: |
        aws ecr get-login-password --region eu-central-1 --debug

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login -u AWS --password-stdin 352507159828.dkr.ecr.eu-central-1.amazonaws.com

    - name: Build, tag, and push image to Amazon ECR
      run: |
        IMAGE_TAG=latest
        docker build -t ue141:$IMAGE_TAG .
        docker tag ue141:$IMAGE_TAG 352507159828.dkr.ecr.eu-central-1.amazonaws.com/ue141:$IMAGE_TAG
        docker push 352507159828.dkr.ecr.eu-central-1.amazonaws.com/ue141:$IMAGE_TAG
